apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: monorepo
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: frontend-cont
        image: luxcrift/frontend:1.0.0
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  namespace: monorepo
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: shopping-cont
        image: luxcrift/shopping:1.0.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: monorepo
  labels:
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: products-cont
        image: luxcrift/products:1.0.0

