apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: monorepo
spec:
  selector:
    app: challenge
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 31000
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: monorepo
spec:
  selector:
    app: challenge
  ports:
  - port: 3002
    targetPort: 80
    nodePort: 31002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: monorepo
spec:
  selector:
    app: challenge
  ports:
  - port: 3001
    targetPort: 80
    nodePort: 31001
  type: NodePort